# Generated by Django 5.2.4 on 2026-02-08 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('main', 'Main Campus'), ('town', 'Town Campus'), ('kitengela', 'Kitengela Campus'), ('western', 'Western Campus')], max_length=20)),
                ('faculty', models.CharField(choices=[('computing', 'Faculty of Computing & Information Management'), ('business', 'School of Business'), ('education', 'School of Education'), ('arts', 'School of Arts & Social Sciences')], max_length=50)),
                ('program', models.CharField(choices=[('bsd', 'Bachelor of Science in Data Science (BSD)'), ('bbit', 'Bachelor of Business Information Technology (BBIT)'), ('bisf', 'Bachelor of Information Security & Forensics (BISF)'), ('bac', 'Bachelor of Applied Communication (BAC)'), ('bcom', 'Bachelor of Commerce (BCom)'), ('procurement', 'Bachelor of Procurement and Logistics'), ('education', 'Bachelor of Education'), ('psychology', 'Bachelor of Arts in Counselling Psychology')], max_length=50)),
                ('year', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5+'), ('na', 'N/A')], max_length=20)),
                ('bio', models.TextField(blank=True, max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('alumni', 'Alumni')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
