# Generated by Django 5.2.4 on 2026-02-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
