# Generated by Django 5.2.4 on 2026-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('notes', '📝 Notes'), ('past_papers', '📄 Past Papers'), ('textbooks', '📚 Textbooks'), ('tutorials', '🎥 Video Tutorials'), ('projects', '💻 Projects'), ('research', '🔬 Research Papers')], max_length=20),
        ),
    ]
