# Generated by Django 5.2.4 on 2026-03-02 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0006_alter_resource_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='Where the event is happening', max_length=200)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('social', 'Social'), ('sports', 'Sports'), ('career', 'Career'), ('cultural', 'Cultural'), ('workshop', 'Workshop'), ('club', 'Club'), ('other', 'Other')], default='social', max_length=20)),
                ('event_link', models.URLField(blank=True, help_text='Link for registration or more info', null=True)),
                ('date', models.DateField(help_text='When is the event?')),
                ('time', models.TimeField(help_text='What time does it start?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
