# Generated by Django 5.2.4 on 2026-03-14 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0007_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('computing', 'Faculty of Computing & Informatics'), ('business', 'School of Business'), ('education', 'School of Education'), ('arts', 'School of Arts & Social Sciences'), ('registry', 'Registry'), ('finance', 'Finance Department'), ('hr', 'Human Resources'), ('library', 'Library Services'), ('it', 'IT Services')], max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
